before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/utilities/ci-tools

include:
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/all.yml'


stages:
    - build_cross_820_dev
    - deploy_cross_820_dev
    - build_cross_865_dev
    - deploy_cross_865_dev